apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image
  labels: 
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:  
        app: my-app
    spec:
      containers:
      - name: myapp
        image: docker.io/akashan/docker-repository:99
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
