---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: first-image
 labels:
  app: my-app
spec:
 replicas: 2
 selector:
  matchLabels:
   app: my-app
 template:
  metadata:
   labels:
    app: my-app
  spec:
   containers:
   - name: my-app
     image: docker.io/akashan/docker-repository:99
     ports:
     - containerPort: 8080
