apiVersion: apps/v1
kind: 
metadata:
  name: my-image
  labels: run=load-balancer-example
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:  run=load-balancer-example
        app: my-app
    spec:
      containers:
      - name: myapp
        image:  docker.io/akashan/docker-repository:99
        ports: 8080/TCP
        - containerPort: 80
